links_to_fsp1:
  - talondx-001/slim-tx-rx/fs-tx0 -> talondx-001/slim-tx-rx/fs-rx0
  - talondx-002/slim-tx-rx/fs-tx0 -> talondx-001/slim-tx-rx/fs-rx1
  - talondx-003/slim-tx-rx/fs-tx0 -> talondx-001/slim-tx-rx/fs-rx2
  - talondx-004/slim-tx-rx/fs-tx0 -> talondx-001/slim-tx-rx/fs-rx3
  - talondx-005/slim-tx-rx/fs-tx0 -> talondx-001/slim-tx-rx/fs-rx4 [x]
  - talondx-006/slim-tx-rx/fs-tx0 -> talondx-001/slim-tx-rx/fs-rx5 [x]
  - talondx-007/slim-tx-rx/fs-tx0 -> talondx-001/slim-tx-rx/fs-rx6 [x]
  - talondx-008/slim-tx-rx/fs-tx0 -> talondx-001/slim-tx-rx/fs-rx7 [x]
links_to_fsp2:
  - talondx-001/slim-tx-rx/fs-tx1 -> talondx-002/slim-tx-rx/fs-rx0 [x]
  - talondx-002/slim-tx-rx/fs-tx1 -> talondx-002/slim-tx-rx/fs-rx1 [x]
  - talondx-003/slim-tx-rx/fs-tx1 -> talondx-002/slim-tx-rx/fs-rx2 [x]
  - talondx-004/slim-tx-rx/fs-tx1 -> talondx-002/slim-tx-rx/fs-rx3 [x]
  - talondx-005/slim-tx-rx/fs-tx1 -> talondx-002/slim-tx-rx/fs-rx4 [x]
  - talondx-006/slim-tx-rx/fs-tx1 -> talondx-002/slim-tx-rx/fs-rx5 [x]
  - talondx-007/slim-tx-rx/fs-tx1 -> talondx-002/slim-tx-rx/fs-rx6 [x]
  - talondx-008/slim-tx-rx/fs-tx1 -> talondx-002/slim-tx-rx/fs-rx7 [x]
links_to_fsp3:
  - talondx-001/slim-tx-rx/fs-tx2 -> talondx-003/slim-tx-rx/fs-rx0 [x]
  - talondx-002/slim-tx-rx/fs-tx2 -> talondx-003/slim-tx-rx/fs-rx1 [x]
  - talondx-003/slim-tx-rx/fs-tx2 -> talondx-003/slim-tx-rx/fs-rx2 [x]
  - talondx-004/slim-tx-rx/fs-tx2 -> talondx-003/slim-tx-rx/fs-rx3 [x]
  - talondx-005/slim-tx-rx/fs-tx2 -> talondx-003/slim-tx-rx/fs-rx4 [x]
  - talondx-006/slim-tx-rx/fs-tx2 -> talondx-003/slim-tx-rx/fs-rx5 [x]
  - talondx-007/slim-tx-rx/fs-tx2 -> talondx-003/slim-tx-rx/fs-rx6 [x]
  - talondx-008/slim-tx-rx/fs-tx2 -> talondx-003/slim-tx-rx/fs-rx7 [x]
links_to_fsp4:
  - talondx-001/slim-tx-rx/fs-tx3 -> talondx-004/slim-tx-rx/fs-rx0 [x]
  - talondx-002/slim-tx-rx/fs-tx3 -> talondx-004/slim-tx-rx/fs-rx1 [x]
  - talondx-003/slim-tx-rx/fs-tx3 -> talondx-004/slim-tx-rx/fs-rx2 [x]
  - talondx-004/slim-tx-rx/fs-tx3 -> talondx-004/slim-tx-rx/fs-rx3 [x]
  - talondx-005/slim-tx-rx/fs-tx3 -> talondx-004/slim-tx-rx/fs-rx4 [x]
  - talondx-006/slim-tx-rx/fs-tx3 -> talondx-004/slim-tx-rx/fs-rx5 [x]
  - talondx-007/slim-tx-rx/fs-tx3 -> talondx-004/slim-tx-rx/fs-rx6 [x]
  - talondx-008/slim-tx-rx/fs-tx3 -> talondx-004/slim-tx-rx/fs-rx7 [x]
links_to_fsp5:
  - talondx-001/slim-tx-rx/fs-tx4 -> talondx-005/slim-tx-rx/fs-rx0 [x]
  - talondx-002/slim-tx-rx/fs-tx4 -> talondx-005/slim-tx-rx/fs-rx1 [x]
  - talondx-003/slim-tx-rx/fs-tx4 -> talondx-005/slim-tx-rx/fs-rx2 [x]
  - talondx-004/slim-tx-rx/fs-tx4 -> talondx-005/slim-tx-rx/fs-rx3 [x]
  - talondx-005/slim-tx-rx/fs-tx4 -> talondx-005/slim-tx-rx/fs-rx4 [x]
  - talondx-006/slim-tx-rx/fs-tx4 -> talondx-005/slim-tx-rx/fs-rx5 [x]
  - talondx-007/slim-tx-rx/fs-tx4 -> talondx-005/slim-tx-rx/fs-rx6 [x]
  - talondx-008/slim-tx-rx/fs-tx4 -> talondx-005/slim-tx-rx/fs-rx7 [x]
links_to_fsp6:
  - talondx-001/slim-tx-rx/fs-tx5 -> talondx-006/slim-tx-rx/fs-rx0 [x]
  - talondx-002/slim-tx-rx/fs-tx5 -> talondx-006/slim-tx-rx/fs-rx1 [x]
  - talondx-003/slim-tx-rx/fs-tx5 -> talondx-006/slim-tx-rx/fs-rx2 [x]
  - talondx-004/slim-tx-rx/fs-tx5 -> talondx-006/slim-tx-rx/fs-rx3 [x]
  - talondx-005/slim-tx-rx/fs-tx5 -> talondx-006/slim-tx-rx/fs-rx4 [x]
  - talondx-006/slim-tx-rx/fs-tx5 -> talondx-006/slim-tx-rx/fs-rx5 [x]
  - talondx-007/slim-tx-rx/fs-tx5 -> talondx-006/slim-tx-rx/fs-rx6 [x]
  - talondx-008/slim-tx-rx/fs-tx5 -> talondx-006/slim-tx-rx/fs-rx7 [x]
links_to_fsp7:
  - talondx-001/slim-tx-rx/fs-tx6 -> talondx-007/slim-tx-rx/fs-rx0 [x]
  - talondx-002/slim-tx-rx/fs-tx6 -> talondx-007/slim-tx-rx/fs-rx1 [x]
  - talondx-003/slim-tx-rx/fs-tx6 -> talondx-007/slim-tx-rx/fs-rx2 [x]
  - talondx-004/slim-tx-rx/fs-tx6 -> talondx-007/slim-tx-rx/fs-rx3 [x]
  - talondx-005/slim-tx-rx/fs-tx6 -> talondx-007/slim-tx-rx/fs-rx4 [x]
  - talondx-006/slim-tx-rx/fs-tx6 -> talondx-007/slim-tx-rx/fs-rx5 [x]
  - talondx-007/slim-tx-rx/fs-tx6 -> talondx-007/slim-tx-rx/fs-rx6 [x]
  - talondx-008/slim-tx-rx/fs-tx6 -> talondx-007/slim-tx-rx/fs-rx7 [x]
links_to_fsp8:
  - talondx-001/slim-tx-rx/fs-tx7 -> talondx-008/slim-tx-rx/fs-rx0 [x]
  - talondx-002/slim-tx-rx/fs-tx7 -> talondx-008/slim-tx-rx/fs-rx1 [x]
  - talondx-003/slim-tx-rx/fs-tx7 -> talondx-008/slim-tx-rx/fs-rx2 [x]
  - talondx-004/slim-tx-rx/fs-tx7 -> talondx-008/slim-tx-rx/fs-rx3 [x]
  - talondx-005/slim-tx-rx/fs-tx7 -> talondx-008/slim-tx-rx/fs-rx4 [x]
  - talondx-006/slim-tx-rx/fs-tx7 -> talondx-008/slim-tx-rx/fs-rx5 [x]
  - talondx-007/slim-tx-rx/fs-tx7 -> talondx-008/slim-tx-rx/fs-rx6 [x]
  - talondx-008/slim-tx-rx/fs-tx7 -> talondx-008/slim-tx-rx/fs-rx7 [x]