apiVersion: v2
name: ska-mid-psi
description: A Helm chart for Kubernetes MVP Mid
type: application
version: 0.1.0
appVersion: 0.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  # TARANTA SUITE
  - name: ska-tango-taranta
    version: 2.18.1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-tangogql-ariadne
    version: 1.0.7
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-taranta-auth
    version: 0.3.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: global.taranta_auth_enabled

  - name: ska-tango-base
    version: 0.4.23
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-tango-base.enabled
  - name: ska-tango-util
    version: 0.4.23
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-mid-cbf-fhs-vcc
    version: 0.3.2
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-mid-cbf-emulators
    version: 0.7.4
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-mid-cbf-mcs
    version: 1.5.0-dev.c5266611b
    repository: https://gitlab.com/api/v4/projects/12488466/packages/helm/dev
  - name: ska-mid-cbf-terabox-mgmt
    version: 0.0.1-dev.c94a4c10e
    repository: https://gitlab.com/api/v4/projects/78064559/packages/helm/dev
