apiVersion: v2
name: ska-mid-psi-dish-lmc
description: A Helm chart for deploying Dish LMC 
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  # Dish LMC
  - name: ska-dish-lmc
    version: 5.0.1-rc1
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-dish-lmc.enabled
