## tmc-mid
display: ":0"
xauthority: "~/.Xauthority"

global:
  dishes: ["001"]
tmc-mid:
  enabled: true
  global:
    namespace_dish:
      dish_names:
      - mid-dish/dish-manager/SKA001
  telescope: SKA-mid
  ska-tango-base:
    enabled: false
  deviceServers:
    centralnode:
      DishIDs:
      - SKA001
    mocks:
      enabled: false
      dish: false
      csp: false
      sdp: false
    dishleafnode:
      enabled: true
      instances:
      - '001'
    subarraynode:
      DishIDs:
      - SKA001
    CspScanInterfaceURL: "https://schema.skao.int/ska-csp-scan/2.2"