## tmc-mid
display: ":0"
xauthority: "~/.Xauthority"

global:
  dishes: ["SKA001", "SKA036", "SKA063", "SKA100"]
tmc-mid:
  enabled: true
  telescope: SKA-mid
  ska-tango-base:
    enabled: false
  deviceServers:
    mocks:
      enabled: true
      dish: true
      csp: false
      sdp: false
    centralnode:
      DishVccConfig:
        DishVccUri: "car://gitlab.com/ska-telescope/ska-telmodel-data?0.1.0-rc-mid-itf#tmdata"
        DishVccFilePath: "instrument/ska1_mid_itf/ska-mid-cbf-system-parameters.json"
      DishIDs: ["SKA001","SKA036","SKA063","SKA100"]
    dishleafnode:
      enabled: true
      instances:
      - '001'
      - '036'
      - '063'
      - '100'
    subarraynode:
      DishIDs:
      - SKA001
      - SKA036
      - SKA063
      - SKA100

