display: ":0"
xauthority: "~/.Xauthority"

global:
  dishes: &dishes ["001", "036", "063", "100"]
  dishids: &dish_ids ["SKA001", "SKA036", "SKA063", "SKA100"]
tmc-mid:
  enabled: true
  subarray_count: 1
  global:
    namespace_dish:
      dish_names:
      - mid-dish/dish-manager/SKA001
      - mid-dish/dish-manager/SKA036
      - mid-dish/dish-manager/SKA063
      - mid-dish/dish-manager/SKA100
  telescope: SKA-mid
  ska-tango-base:
    enabled: false
  deviceServers:
    centralnode:
      DishVccConfig:
        DishVccUri: "gitlab://gitlab.com/ska-telescope/ska-mid-psi?main#tmdata"
        DishVccFilePath: "instrument/ska1_mid_psi/aa05/ska-mid-cbf-system-parameters-itf.json"
      DishIDs: *dish_ids # use the dish_ids list defined under global instead of repeating here
    mocks:
      enabled: false
      dish: false
      csp: false
      sdp: false
    dishleafnode:
      enabled: true
      instances: *dishes # use the dishes list defined under global instead of repeating here
    subarraynode:
      DishIDs: *dish_ids # use the dish_ids list defined under global instead of repeating here
      CspScanInterfaceURL: "https://schema.skao.int/ska-csp-scan/2.2"
      CommandTimeOutDefault: 240
    sdpsubarrayleafnode:
      CommandTimeOutDefault: 240
    cspsubarrayleafnode:
      CommandTimeOutDefault: 240
    resourcemonitor:
      MidSubarrayNodeFQDNs: ["mid-tmc/subarray/01"]
      DishIDs: *dish_ids # use the dish_ids list defined under global instead of repeating here
