## tmc-mid
display: ":0"
xauthority: "~/.Xauthority"

global:
  dishes: ["100"]
tmc-mid:
  enabled: true
  global:
    namespace_dish:
      dish_names:
      - mid-dish/dish-manager/SKA100
  telescope: SKA-mid
  ska-tango-base:
    enabled: false
  deviceServers:
    centralnode:
      DishIDs:
      - SKA100
    mocks:
      enabled: false
      dish: false
      csp: false
      sdp: false
    dishleafnode:
      enabled: true
      instances:
      - '100'
    subarraynode:
      DishIDs:
      - SKA100