## tmc-mid
display: ":0"
xauthority: "~/.Xauthority"

global:
  dishes: ["001", "036", "063", "100"]
tmc-mid:
  enabled: true
  telescope: SKA-mid
  ska-tango-base:
    enabled: false
  deviceServers:
    mocks:
      enabled: true
      dish: true
      csp: false
      sdp: false
    dishleafnode:
      enabled: true
      instances:
      - '001'
      - '036'
      - '063'
      - '100'
    subarraynode:
      DishIDs:
      - SKA001
      - SKA036
      - SKA063
      - SKA100

