## tmc-mid
display: ":0"
xauthority: "~/.Xauthority"

global:
  dishes: ["001", "036", "063", "100"]
  namespace_dish:
    dish_names: ['mid-dish/dish-manager/SKA001','mid-dish/dish-manager/SKA036','mid-dish/dish-manager/SKA063','mid-dish/dish-manager/SKA100']
tmc-mid:
  enabled: true
  telescope: SKA-mid
  ska-tango-base:
    enabled: false
  deviceServers:
    mocks:
      enabled: false
      dish: false
      csp: false
      sdp: false
      