## tmc-mid
display: ":0"
xauthority: "~/.Xauthority"

ska-tmc-mid:
  enabled: true
  telescope: SKA-mid
  ska-tango-base:
    enabled: false
  deviceServers:
    mocks:
      enabled: true
      dish: true
      csp: false
      sdp: false