display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: false
  operator: true
  exposeAllDS: true
  dish_suffix: "elt/master"
  annotations:
    app.gitlab.com/app: ska-mid-psi
    app.gitlab.com/env: ska
  taranta_auth_enabled: false
  taranta_dashboard_enabled: true
  sub-system:
    tango-base:
      enabled: false
    ska-tango-base:
      enabled: false
    ska-taranta:
      enabled: false
  retry:
    - "--sleep=3"
    - "--tries=100"
  tango_host: databaseds-tango-base:10000
  device_server_port: 45450
  cluster_domain: cluster.local
  data-product-pvc-name: test-sdp-pvc
  tangodb_fqdn: localhost
  tangodb_port: 10000
  raw_user_account: ""
  raw_user_pass: ""
  kafka_host: ska-mid-psi-kafka

ska-tango-base:
  enabled: true
  vnc:
    replicas: 1
    enabled: true
  tangorest:
    enabled: true
    replicas: 1
  tangodb:
    use_pv: true

ska-mid-cbf-fhs-vcc:
  enabled: true
  ska-tango-base:
    enabled: false
  midcbf:
    image:
      registry: harbor.skao.int/production
      image: ska-mid-cbf-fhs-vcc
      tag: 0.3.2
      pullPolicy: Always
  standaloneSimulator: false
  properties:
    deviceVersionNum: "0.3.0"
    deviceGitlabHash: "0"
    simulationMode: "0"
    emulatorBaseUrl: "ska-mid-cbf.svc.cluster.local:5001"
    bitstreamPath: &bitstreamPath "/app/mnt/bitstream"
    bitstreamId: &bitstreamId "agilex-vcc"
    bitstreamVersion: &bitstreamVer "0.1.2"
    emulatorId: &emulatorId "fhs-vcc-emulator-{{.deviceId}}"
    emulatorIpBlockId: ""
    firmwareIpBlockId: ""
    healthMonitorPollInterval: "3"
  numVccUnits: 2
  VCCUnits:
  - unitNum: 1
    emulationMode: '1'
    instancesRange: [1, 6]
    networkSwitchId: 192.168.7.31
    bmc_endpoint: 127.0.1.1
  - unitNum: 2
    emulationMode: '1'
    instancesRange: [7, 12]
    networkSwitchId: 192.168.7.31
    bmc_endpoint: 127.0.1.1

ska-mid-cbf-emulators:
  enabled: true
  emulator:
    app_label: ska-mid-cbf-fhs-system-tests
    image:
      repository: registry.gitlab.com/ska-telescope/ska-mid-cbf-emulators/ska-mid-cbf-emulators-emulator
      tag: 0.7.4
      pullPolicy: Always
    verbosity: 3
  injector:
    app_label: ska-mid-cbf-fhs-system-tests
    image:
      repository: registry.gitlab.com/ska-telescope/ska-mid-cbf-emulators/ska-mid-cbf-emulators-injector
      tag: 0.7.4
      pullPolicy: Always

  properties:
    bitstreamPath: *bitstreamPath
    bitstreamId: *bitstreamId
    bitstreamVersion: *bitstreamVer
    emulatorId: *emulatorId

  instances:
  - name: fhs-vcc-1
    deviceId: "1"
  - name: fhs-vcc-2
    deviceId: "2"
  - name: fhs-vcc-3
    deviceId: "3"
  - name: fhs-vcc-4
    deviceId: "4"
  - name: fhs-vcc-5
    deviceId: "5"
  - name: fhs-vcc-6
    deviceId: "6"
  - name: fhs-vcc-1
    deviceId: "7"
  - name: fhs-vcc-2
    deviceId: "8"
  - name: fhs-vcc-3
    deviceId: "9"
  - name: fhs-vcc-4
    deviceId: "10"
  - name: fhs-vcc-5
    deviceId: "11"
  - name: fhs-vcc-6
    deviceId: "12"

  rabbitmq:
    host: rabbitmq-service

ska-mid-cbf-mcs:
  enabled: true
  ska-tango-base:
    enabled: false
  midcbf:
    image:
      registry: registry.gitlab.com/ska-telescope/ska-mid-cbf-mcs
      image: ska-mid-cbf-mcs
      tag: 1.5.0-dev.c5266611b
      pullPolicy: Always
  subarrays: 16
  vcc:
    units: 2
  fsp:
    units: 1

ska-mid-cbf-terabox-mgmt:
  # the default tango properties in each device. optionally provide a default, global value
  properties:
    deviceId: "000"
    deviceVersionNum: "0.0.1"
    simulationMode: "0"
    emulationMode: "{{ .emulationMode }}"
    prometheus: "{{ .prometheus }}"
    nodeExporter: "{{ .nodeExporter }}"
    fhsPrometheusExporter: "{{ .fhsPrometheusExporter }}"

  # the devices in each stack. optionally override any property defined in `properties`. to add extra properties, provide a `properties` dict
  deviceCommand: "FhsTeraboxMgmtDeviceServer"
  devices: []

  # the FHSMonitor device
  teraboxMgmtDevice:
    name: "FhsMonitorDevice"
    path: "fhs-monitor/fhs-{{.fhsName}}/0"
    properties:
      - name: logging_level
        values:
          - "INFO"

  # the top-level stacks, one for every device id. optionally override any property defined in `properties` (if it hasn't been overridden at the device level)
  teraBoxMgmtInstances:
    - fhsName: "vcc-01"
      emulationMode: "1"

  prometheusUrl: "http://0.0.0.0:9090"

