image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MINIKUBE: "false"
  TANGO_HOST: databaseds-tango-base:10000
  CLUSTER_DOMAIN: cluster.local
  SPFRX_ADDRESS: 192.168.8.200
  TANGO_INSTANCE: spfrx-20
  SPFRX_BIN: /usr/local/bin
  SPFRX_LOCAL_DIR: artifacts
  SPFRX_LOGGING_LEVEL: 4
  SPFRX_SCRIPTS_DIR: scripts
  SPFRX_CONSOLE_VER: 0.1.0
  DISH_ID: ska001
  DISH_LMC_ENABLED: false

stages:
  - lint
  - on_demand_psi
  - build
  - deploy
  - join-reports
  - pages
  - publish
  - scan
  - cleanup

include:

  # Helm Charts
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

  # .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

  # changelog release page
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/changelog.gitlab-ci.yml'

  # deploy steps to psi mid
  - local: "/.gitlab/ci/psi-mid.gitlab-ci.yml"
    
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/xray-publish.gitlab-ci.yml'

  # Docs pages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs-pages.gitlab-ci.yml'

  # .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

docs-pages:
  rules:
    - when: never


