image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MINIKUBE: "false"
stages:
  - lint
  - on_demand_psi
  - deploy-spfrx
  - build
  - deploy
  - join-reports
  - pages
  - publish
  - scan
  - cleanup
  

spfrx-deployer:
  stage: deploy-spfrx
  extends:
    - .mid
  variables:
    KUBE_NAMESPACE: "ci-ska-mid-cbf-sys-tests-$CI_PIPELINE_ID-$GITLAB_USER_LOGIN"
    KUBE_NAMESPACE_SDP: "$KUBE_NAMESPACE-sdp"
  tags:
    - k8srunner-psi-mid
  script:
    - git clone --recursive https://gitlab.com/ska-telescope/ska-mid-dish-spfrx-talondx-console.git
    - cd ska-mid-dish-spfrx-talondx-console
    - make generate-spfrx-config
    - make config-db SPFRX_TANGO_HOST=databaseds-tango-base.$KUBE_NAMESPACE.svc.cluster.local:10000
    - sleep 10
    - make spfrx-start SPFRX_TANGO_HOST=databaseds-tango-base.$KUBE_NAMESPACE.svc.cluster.local:10000
    - sleep 240
  rules:
    - when: manual
  needs:
    - job: psi-mid-on-demand-deploy


include:

  # Helm Charts
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

  # .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

  # changelog release page
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/changelog.gitlab-ci.yml'

  # deploy steps to psi mid
  - local: "/.gitlab/ci/psi-mid.gitlab-ci.yml"
    
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/xray-publish.gitlab-ci.yml'

  # Docs pages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs-pages.gitlab-ci.yml'

  # .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

docs-pages:
  rules:
    - when: never


