apiVersion: v1
kind: Pod
metadata:
  name: spfrx-deployer
spec:
  containers:
  - name: spfrx-deployer
    image: artefact.skao.int/ska-mid-dish-spfrx-talondx-console-deploy:0.0.5
    env:
      - name: TANGO_HOST
        value: TANGO_HOST_VALUE
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash","-c"]
    args: ["tail -f /dev/null"]

