apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdp-products
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdp-products
  namespace: {{ .Values.global.sdp.processingNamespace }}
  labels:
    skao.int/clone-pvc: sdp-products
    skao.int/clone-pvc-namespace: {{ .Release.Namespace }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
