db: databaseds-tango-base.{{Release.Namespace}}.svc.cluster.local:10000
manager: mid-eda/cm/01
archiver: mid-eda/es/01

configuration:
  - class: TalonBoard
    attributes:
      State:
        code_push_event: true
      simulationMode:
        archive_period: 60000
        polling_period: 30000
      FpgaDieTemperature:
        archive_period: 60000
        polling_period: 30000
      HumiditySensorTemperature:
        archive_period: 60000
        polling_period: 30000
      DIMMTemperatures:
        archive_period: 60000
        polling_period: 30000
      MboTxTemperatures:
        archive_period: 60000
        polling_period: 30000
      MboTxVccVoltages:
        archive_period: 60000
        polling_period: 30000
      MboRxVccVoltages:
        archive_period: 60000
        polling_period: 30000
      FansFault:
        archive_period: 60000
        polling_period: 30000
