.mid:
  variables:
    CONFIG: mid

.deploy:
  stage: deploy
  variables:
    HELM_RELEASE: "test-$CI_PIPELINE_ID"
    KUBE_NAMESPACE: "ci-ska-mid-psi-$CI_PIPELINE_ID-$GITLAB_USER_LOGIN"
    KUBE_NAMESPACE_SDP: "$KUBE_NAMESPACE-sdp"
    K8S_AUTH_NAMESPACES: "$KUBE_NAMESPACE $KUBE_NAMESPACE_SDP"
    K8S_AUTH_SERVICE_ACCOUNT: "ci-svc-psi-$CI_PIPELINE_ID"
    SKA_TANGO_ARCHIVER: true
    VALUES: values.yaml
  script:
    - echo $CI_JOB_NAME - $CI_JOB_STAGE
    - echo "Make config dump"
    - make vars
    - |
      if [ "$K8S_INSTALL_FROM_CAR" != "true" ]; then
       echo "Install Skampi Charts"
       make k8s-install-chart
      else
        echo "Install Skampi Charts"
        make k8s-install-chart-car
      fi
    - echo "Get namespace resources"
    - make k8s-get
    - echo "Wait namespace resources"
    - make k8s-wait
    - |
      if [ "$SKA_TANGO_ARCHIVER" == "true" ]; then
        echo "Add attributes to EDA for archiving"
        echo "make eda-add-attributes KUBE_NAMESPACE=$KUBE_NAMESPACE"
        make eda-add-attributes KUBE_NAMESPACE=$KUBE_NAMESPACE
      else
        echo "SKA_TANGO_ARCHIVER is false"
      fi

.info:
  stage: deploy
  variables:
    K8S_CHART: "ska-$CONFIG"
    HELM_RELEASE: "test-$CI_PIPELINE_ID"
    KUBE_NAMESPACE: "ci-ska-mid-psi-$CI_PIPELINE_ID-$GITLAB_USER_LOGIN"
    KUBE_NAMESPACE_SDP: "$KUBE_NAMESPACE-sdp"
  script:
    - echo "Get namespace resources"
    - make k8s-get
    - echo "Get SDP namespace resources"
    - make k8s-get KUBE_NAMESPACE=${KUBE_NAMESPACE}-sdp
    - make k8s-info
    - make k8s-info KUBE_NAMESPACE=${KUBE_NAMESPACE}-sdp

.cleanup:
  stage: cleanup
  variables:
    K8S_CHART: "ska-$CONFIG"
    HELM_RELEASE: "test-$CI_PIPELINE_ID"
    KUBE_NAMESPACE: "ci-ska-mid-psi-$CI_PIPELINE_ID-$GITLAB_USER_LOGIN"
    KUBE_NAMESPACE_SDP: "$KUBE_NAMESPACE-sdp"
    ARCHIVE_CONFIG: "$ARCHIVE_CONFIG"
  script: &cleanup_script
    - echo $CI_JOB_NAME - $CI_JOB_STAGE
    - echo "Make config dump" ; make vars
    - |
      if [ "$SKA_TANGO_ARCHIVER" == "true" ]; then
        echo "Remove attributes from being archived in EDA"
        echo "make eda-remove-attributes KUBE_NAMESPACE=${KUBE_NAMESPACE} ARCHIVE_CONFIG=${ARCHIVE_CONFIG}"
        make eda-remove-attributes KUBE_NAMESPACE=${KUBE_NAMESPACE} ARCHIVE_CONFIG=${ARCHIVE_CONFIG}
      else
        echo "SKA_TANGO_ARCHIVER is false"
    - fi
    - make k8s-uninstall-chart || true
    - |
      if [ "$KEEP_NAMESPACE" != "true" ]; then
        make k8s-delete-namespace
      fi

.redeploy:
  extends:
    - .deploy
  before_script: *cleanup_script

.psi_mid_on_demand:
  tags:
    - k8srunner-psi-mid
  stage: on_demand_psi
  extends:
    - .mid
  variables:
    VALUES: "values.yml"
    INGRESS_HOST: "INGRESS.IP.ADDRESS"
    HELM_RELEASE: "test-$CI_PIPELINE_ID"
    KUBE_NAMESPACE: "ci-ska-mid-psi-$CI_PIPELINE_ID-$GITLAB_USER_LOGIN"
    KUBE_NAMESPACE_SDP: "$KUBE_NAMESPACE-sdp"
    SERVICE_ACCOUNT: "ci-svc-psi-$CI_PIPELINE_ID"

psi-mid-on-demand-deploy:
  extends:
    - .deploy
    - .psi_mid_on_demand
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
  allow_failure: true
  environment:
    name: psi-mid/ska-$CI_COMMIT_REF_NAME

psi-mid-on-demand-info:
  extends:
    - .info
    - .psi_mid_on_demand
  when: manual

psi-mid-on-demand-destroy:
  stage: cleanup
  extends:
    - .cleanup
    - .psi_mid_on_demand
  when: manual
  environment:
    name: psi-mid/ska-$CI_COMMIT_REF_NAME
    action: stop

psi-mid-on-demand-redeploy:
  when: manual
  extends:
    - .redeploy
    - .psi_mid_on_demand
  environment:
    name: psi-mid/ska-$CI_COMMIT_REF_NAME

